import COLORS from "../../constans/colors";
import { StyleSheet, Dimensions, Platform } from "react-native";

export default StyleSheet.create({
  listGrupContainer: {
    marginVertical: 10,
    marginHorizontal: 10,
    backgroundColor: "#ffffff",
    // paddingBottom: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },

    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  durum: {
    color: "#fff",

    textAlign: "center",
  },
  locationContainer: { flexDirection: "row", alignItems: "center" },
  address: { flexDirection: "row", alignItems: "center" },
  txt: { textAlign: "center", fontWeight: "bold" },
  durumContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 40,
    flexDirection: "column",
  },
  durumColor: {
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 20,
    // padding: 10,
    marginBottom: 5,
    borderRadius: 4,
  },
  price: {
    marginTop: 10,
    color: COLORS.primary,
    fontWeight: "bold",
    textAlign: "center",
  },
  chipsScrollView: {
    // position: "absolute",
    // top: Platform.OS === "ios" ? 90 : 80,
    paddingHorizontal: 10,
    marginTop: 10,
    width: "100%",
  },
  chipsIcon: {
    marginRight: 5,
  },
  chipsItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 8,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    height: 35,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  scrollView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 10,
  },
  kategori: {
    fontSize: 15,
    fontWeight: "bold",
    // color: COLORS.text,
  },
  container: {
    flexDirection: "row",
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
  filterButton: {
    borderRadius: 15,
    padding: 8,
    paddingLeft: 24,
    paddingRight: 24,
    marginRight: 8,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
    borderWidth: 1,
    borderColor: "#ccc",
  },
});
