export const DISTRICTS_CITY = "DSC/DISTRICTS_CITY/LOAD";
export const DISTRICTS_CITY_SUCCESS = "DSC/DISTRICTS_CITY/LOAD_SUCCESS";
export const DISTRICTS_CITY_FAIL = "DSC/DISTRICTS_CITY/LOAD_FAIL";
export const DISTRICTS_CITY_URL = "/General/Cities/GetAllWithDistricts";
