export const ORDERS_GET_ALL_PENDING_OFFERS = "ORDERS/GET_ALL/PENDING_OFFERS";
export const ORDERS_GET_ALL_PENDING_OFFERS_SUCCESS =
  "ORDERS/GET_ALL/PENDING_OFFERS_SUCCESS";
export const ORDERS_GET_ALL_PENDING_OFFERS_FAIL =
  "ORDERS/GET_ALL/PENDING_OFFERS_FAIL";
export const ORDERS_GET_ALL_PENDING_OFFERS_URL =
  "/driver/orders/GetAllPendingOffers";

export const ORDERS_GET_PENDING_OFFER_DETAIL =
  "ORDERS_GET/PENDING_OFFER/DETAIL";
export const ORDERS_GET_PENDING_OFFER_DETAIL_SUCCESS =
  "ORDERS_GET/PENDING_OFFER/DETAIL_SUCCESS";
export const ORDERS_GET_PENDING_OFFER_DETAIL_FAIL =
  "ORDERS_GET/PENDING_OFFER/DETAIL_FAIL";
export const ORDERS_GET_PENDING_OFFER_DETAIL_URL =
  "/driver/orders/GetPendingOfferDetail";

export const ORDERS_ASSIGN_GROUP_DRIVER = "ORDERS_ASSIGN/GROUP_DRIVER";
export const ORDERS_ASSIGN_GROUP_DRIVER_SUCCESS =
  "ORDERS_ASSIGN/GROUP_DRIVER_SUCCESS";
export const ORDERS_ASSIGN_GROUP_DRIVER_FAIL =
  "ORDERS_ASSIGN/GROUP_DRIVER_FAIL";
export const ORDERS_ASSIGN_GROUP_DRIVER_URL =
  "/driver/orders/AssignGroupToDriver";

export const DRIVER_ORDERS_GET_ALL_MY_ORDERS =
  "DRIVER_ORDERS/GET_ALL_MY_ORDERS";
export const DRIVER_ORDERS_GET_ALL_MY_ORDERS_SUCCESS =
  "DRIVER_ORDERS/GET_ALL_MY_ORDERS_SUCCESS";
export const DRIVER_ORDERS_GET_ALL_MY_ORDERS_FAIL =
  "DRIVER_ORDERS/GET_ALL_MY_ORDERS_FAIL";
export const DRIVER_ORDERS_GET_ALL_MY_ORDERS_URL =
  "/Driver/Orders/GetAllMyOrders";

export const DRIVER_LOGIN = "DRIVER/LOGIN/LOAD";
export const DRIVER_LOGIN_SUCCESS = "DRIVER/LOGIN/LOAD_SUCCESS";
export const DRIVER_LOGIN_FAIL = "DRIVER/LOGIN/LOAD_FAIL";
export const DRIVER_LOGIN_URL = "/DriverLogin";

export const DRIVER_ORDERS_GET_BY_ID = "DRIVER_ORDERS/GET_BY_ID/LOAD";
export const DRIVER_ORDERS_GET_BY_ID_SUCCESS =
  "DRIVER_ORDERS/GET_BY_ID/LOAD_SUCCESS";
export const DRIVER_ORDERS_GET_BY_ID_FAIL = "DRIVER_ORDERS/GET_BY_ID/LOAD_FAIL";
export const DRIVER_ORDERS_GET_BY_ID_URL = "/Order/Orders/GetByID";
