export const ORDERS_GET_ALL_PENDING_OFFERS = "ORDERS/GET_ALL/PENDING_OFFERS";
export const ORDERS_GET_ALL_PENDING_OFFERS_SUCCESS =
  "ORDERS/GET_ALL/PENDING_OFFERS_SUCCESS";
export const ORDERS_GET_ALL_PENDING_OFFERS_FAIL =
  "ORDERS/GET_ALL/PENDING_OFFERS_FAIL";
export const ORDERS_GET_ALL_PENDING_OFFERS_URL =
  "/driver/orders/GetAllPendingOffers";

export const ORDERS_GET_PENDING_OFFER_DETAIL =
  "ORDERS_GET/PENDING_OFFER/DETAIL";
export const ORDERS_GET_PENDING_OFFER_DETAIL_SUCCESS =
  "ORDERS_GET/PENDING_OFFER/DETAIL_SUCCESS";
export const ORDERS_GET_PENDING_OFFER_DETAIL_FAIL =
  "ORDERS_GET/PENDING_OFFER/DETAIL_FAIL";
export const ORDERS_GET_PENDING_OFFER_DETAIL_URL =
  "/driver/orders/GetPendingOfferDetail";

export const ORDERS_ASSIGN_GROUP_DRIVER = "ORDERS_ASSIGN/GROUP_DRIVER";
export const ORDERS_ASSIGN_GROUP_DRIVER_SUCCESS =
  "ORDERS_ASSIGN/GROUP_DRIVER_SUCCESS";
export const ORDERS_ASSIGN_GROUP_DRIVER_FAIL =
  "ORDERS_ASSIGN/GROUP_DRIVER_FAIL";
export const ORDERS_ASSIGN_GROUP_DRIVER_URL =
  "/driver/orders/AssignGroupToDriver";
