export const VEHICLE_BRANDS_GET_ALL = "VEHICLE_BRANDS/GET_ALL";
export const VEHICLE_BRANDS_GET_ALL_SUCCESS = "VEHICLE_BRANDS/GET_ALL_SUCCESS";
export const VEHICLE_BRANDS_GET_ALL_FAIL = "VEHICLE_BRANDS/GET_ALL_FAIL";
export const VEHICLE_BRANDS_GET_ALL_URL = "/General/VehicleBrands/GetAll";

export const VEHICLE_MODELS_GET_BY_BRAND_ID = "VEHICLE_MODELS/GET_BY_BRAND_ID";
export const VEHICLE_MODELS_GET_BY_BRAND_ID_SUCCESS =
  "VEHICLE_MODELS/GET_BY_BRAND_ID_SUCCESS";
export const VEHICLE_MODELS_GET_BY_BRAND_ID_FAIL =
  "VEHICLE_MODELS/GET_BY_BRAND_ID_FAIL";
export const VEHICLE_MODELS_GET_BY_BRAND_ID_URL =
  "/General/VehicleModels/GetByBrandID";

export const VEHICLE_MODELS_DESI_RATE = "VEHICLE_MODELS/DESI_RATE";
export const VEHICLE_MODELS_DESI_RATE_SUCCESS =
  "VEHICLE_MODELS/DESI_RATE_SUCCESS";
export const VEHICLE_MODELS_DESI_RATE_FAIL = "VEHICLE_MODELS/DESI_RATE_FAIL";
export const VEHICLE_MODELS_DESI_RATE_URL = "/General/VehicleModels/DesiRate";

export const VEHICLE_TYPES_GET_ALL = "VEHICLE_TYPES/GET_ALL";
export const VEHICLE_TYPES_GET_ALL_SUCCESS = "VEHICLE_TYPES/GET_ALL_SUCCESS";
export const VEHICLE_TYPES_GET_ALL_FAIL = "VEHICLE_TYPES/GET_ALL_FAIL";
export const VEHICLE_TYPES_GET_ALL_URL = "/General/VehicleTypes/GetAll";

export const CITIES_GET_ALL = "CITIES/GET_ALL";
export const CITIES_GET_ALL_SUCCESS = "CITIES/GET_ALL_SUCCESS";
export const CITIES_GET_ALL_FAIL = "CITIES/GET_ALL_FAIL";
export const CITIES_GET_ALL_URL = "/General/Cities/GetAll";

export const CITIES_GET_ALL_WITH_DISTRICTS = "CITIES/GET_ALL_WITH_DISTRICTS";
export const CITIES_GET_ALL_WITH_DISTRICTS_SUCCESS =
  "CITIES/GET_ALL_WITH_DISTRICTS_SUCCESS";
export const CITIES_GET_ALL_WITH_DISTRICTS_FAIL =
  "CITIES/GET_ALL_WITH_DISTRICTS_FAIL";
export const CITIES_GET_ALL_WITH_DISTRICTS_URL =
  "/General/Cities/GetAllWithDistricts";

export const DISTRICTS_GET_BY_CITY_ID = "DISTRICTS/GET_BY_CITY_ID";
export const DISTRICTS_GET_BY_CITY_ID_SUCCESS =
  "DISTRICTS/GET_BY_CITY_ID_SUCCESS";
export const DISTRICTS_GET_BY_CITY_ID_FAIL = "DISTRICTS/GET_BY_CITY_ID_FAIL";
export const DISTRICTS_GET_BY_CITY_ID_URL = "/General/Districts/GetByCityID";

export const ADDRESS_SEARCH_BY_KEYWORD = "ADDRESS_SEARCH/BY_KEYWORD";
export const ADDRESS_SEARCH_BY_KEYWORD_SUCCESS =
  "ADDRESS_SEARCH/BY_KEYWORDL_SUCCESS";
export const ADDRESS_SEARCH_BY_KEYWORD_FAIL = "ADDRESS_SEARCH/BY_KEYWORD_FAIL";
export const ADDRESS_SEARCH_BY_KEYWORD_URL =
  "/General/AddressSearch/SearchByKeyword?keyword=";
