export const REGISTER_COMPLATE = "CMP/REGISTER_COMPLATE/LOAD";
export const REGISTER_COMPLATE_SUCCESS = "CMP/REGISTER_USER/LOAD_SUCCESS";
export const REGISTER_COMPLATE_FAIL = "CMP/REGISTER_USER/LOAD_FAIL";
export const REGISTER_COMPLATE_URL = "/Shipper/Shippers/RegisterBeginRequest";
