export const DRIVERS_CREATE = "DRIVERS/CREATE/LOAD";
export const DRIVERS_CREATE_SUCCESS = "DRIVERS/CREATE/LOAD_SUCCESS";
export const DRIVERS_CREATE_FAIL = "DRIVERS/CREATE/LOAD_FAIL";
export const DRIVERS_CREATE_URL = "/Shipper/Drivers/Create";

export const DRIVERS_GET_BY_SHIPPER_ID = "DRIVERS/GET_BY_SHIPPER_ID/LOAD";
export const DRIVERS_GET_BY_SHIPPER_ID_SUCCESS =
  "DRIVERS/GET_BY_SHIPPER_ID/LOAD_SUCCESS";
export const DRIVERS_GET_BY_SHIPPER_ID_FAIL =
  "DRIVERS/GET_BY_SHIPPER_ID/LOAD_FAIL";
export const DRIVERS_GET_BY_SHIPPER_ID_URL = "/Shipper/Drivers/GetByShipperID";

export const VEHICLES_CREATE = "VEHICLES/CREATE/LOAD";
export const VEHICLES_CREATE_SUCCESS = "VEHICLES/CREATE/LOAD_SUCCESS";
export const VEHICLES_CREATE_FAIL = "VEHICLES/CREATE/LOAD_FAIL";
export const VEHICLES_CREATE_URL = "/Shipper/Vehicles/Create";

export const SHIPPERS_REGISTER_BEGIN_REQUEST =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_SUCCESS =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD_SUCCESS";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_FAIL =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD_FAIL";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_URL =
  "/Shipper/Shippers/RegisterBeginRequest";

export const SHIPPERS_REGISTER_COMPLATE = "SHIPPERS/REGISTER_COMPLATE/LOAD";
export const SHIPPERS_REGISTER_COMPLATE_SUCCESS =
  "SHIPPERS/REGISTER_COMPLATE/LOAD_SUCCESS";
export const SHIPPERS_REGISTER_COMPLATE_FAIL =
  "SHIPPERS/REGISTER_COMPLATE/LOAD_FAIL";
export const SHIPPERS_REGISTER_COMPLATE_URL =
  "/Shipper/Shippers/RegisterComplate";

export const SHIPPERS_LOGIN = "SHIPPERS/LOGIN/LOAD";
export const SHIPPERS_LOGIN_SUCCESS = "SHIPPERS/LOGIN/LOAD_SUCCESS";
export const SHIPPERS_LOGIN_FAIL = "SHIPPERS/LOGIN/LOAD_FAIL";
export const SHIPPERS_LOGIN_URL = "/ShipperLogin";

export const VEHICLES_GET_BY_SHIPPER_ID = "VEHICLES/GET_BY_SHIPPER_ID/LOAD";
export const VEHICLES_GET_BY_SHIPPER_ID_SUCCESS =
  "VEHICLES/GET_BY_SHIPPER_ID/LOAD_SUCCESS";
export const VEHICLES_GET_BY_SHIPPER_ID_FAIL =
  "VEHICLES/GET_BY_SHIPPER_ID/LOAD_FAIL";
export const VEHICLES_GET_BY_SHIPPER_ID_URL =
  "/Shipper/Vehicles/GetByShipperID";
