export const DRIVERS_CREATE = "DRIVERS/CREATE/LOAD";
export const DRIVERS_CREATE_SUCCESS = "DRIVERS/CREATE/LOAD_SUCCESS";
export const DRIVERS_CREATE_FAIL = "DRIVERS/CREATE/LOAD_FAIL";
export const DRIVERS_CREATE_URL = "/Shipper/Drivers/Create";

export const DRIVERS_GET_BY_SHIPPER_ID = "DRIVERS/GET_BY_SHIPPER_ID/LOAD";
export const DRIVERS_GET_BY_SHIPPER_ID_SUCCESS =
  "DRIVERS/GET_BY_SHIPPER_ID/LOAD_SUCCESS";
export const DRIVERS_GET_BY_SHIPPER_ID_FAIL =
  "DRIVERS/GET_BY_SHIPPER_ID/LOAD_FAIL";
export const DRIVERS_GET_BY_SHIPPER_ID_URL = "/Shipper/Drivers/GetByShipperID";

export const VEHICLES_CREATE = "VEHICLES/CREATE/LOAD";
export const VEHICLES_CREATE_SUCCESS = "VEHICLES/CREATE/LOAD_SUCCESS";
export const VEHICLES_CREATE_FAIL = "VEHICLES/CREATE/LOAD_FAIL";
export const VEHICLES_CREATE_URL = "/Shipper/Vehicles/Create";

export const SHIPPERS_REGISTER_BEGIN_REQUEST =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_SUCCESS =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD_SUCCESS";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_FAIL =
  "SHIPPERS/REGISTER_BEGIN_REQUEST/LOAD_FAIL";
export const SHIPPERS_REGISTER_BEGIN_REQUEST_URL =
  "/Shipper/Shippers/RegisterBeginRequest";

export const SHIPPERS_REGISTER_COMPLATE = "SHIPPERS/REGISTER_COMPLATE/LOAD";
export const SHIPPERS_REGISTER_COMPLATE_SUCCESS =
  "SHIPPERS/REGISTER_COMPLATE/LOAD_SUCCESS";
export const SHIPPERS_REGISTER_COMPLATE_FAIL =
  "SHIPPERS/REGISTER_COMPLATE/LOAD_FAIL";
export const SHIPPERS_REGISTER_COMPLATE_URL =
  "/Shipper/Shippers/RegisterComplate";

export const SHIPPERS_LOGIN = "SHIPPERS/LOGIN/LOAD";
export const SHIPPERS_LOGIN_SUCCESS = "SHIPPERS/LOGIN/LOAD_SUCCESS";
export const SHIPPERS_LOGIN_FAIL = "SHIPPERS/LOGIN/LOAD_FAIL";
export const SHIPPERS_LOGIN_URL = "/Login";

export const VEHICLES_GET_BY_SHIPPER_ID = "VEHICLES/GET_BY_SHIPPER_ID/LOAD";
export const VEHICLES_GET_BY_SHIPPER_ID_SUCCESS =
  "VEHICLES/GET_BY_SHIPPER_ID/LOAD_SUCCESS";
export const VEHICLES_GET_BY_SHIPPER_ID_FAIL =
  "VEHICLES/GET_BY_SHIPPER_ID/LOAD_FAIL";
export const VEHICLES_GET_BY_SHIPPER_ID_URL =
  "/Shipper/Vehicles/GetByShipperID";

export const SHIPPER_ORDERS_GET_ALL_MY_ORDERS =
  "SHIPPER_ORDERS/GET_ALL_MY_ORDERS/LOAD";
export const SHIPPER_ORDERS_GET_ALL_MY_ORDERS_SUCCESS =
  "SHIPPER_ORDERS/GET_ALL_MY_ORDERS/LOAD_SUCCESS";
export const SHIPPER_ORDERS_GET_ALL_MY_ORDERS_FAIL =
  "SHIPPER_ORDERS/GET_ALL_MY_ORDERS/LOAD_FAIL";
export const SHIPPER_ORDERS_GET_ALL_MY_ORDERS_URL =
  "/Shipper/Orders/GetAllMyOrders";

export const SHIPPER_ORDERS_GET_BY_ID = "SHIPPER_ORDERS/GET_BY_ID/LOAD";
export const SHIPPER_ORDERS_GET_BY_ID_SUCCESS =
  "SHIPPER_ORDERS/GET_BY_ID/LOAD_SUCCESS";
export const SHIPPER_ORDERS_GET_BY_ID_FAIL =
  "SHIPPER_ORDERS/GET_BY_ID/LOAD_FAIL";
export const SHIPPER_ORDERS_GET_BY_ID_URL = "/Order/Orders/GetByID";

export const SHIPPER_ORDERS_PICKUP = "SHIPPER_ORDERS/PICKUP/LOAD";
export const SHIPPER_ORDERS_PICKUP_SUCCESS =
  "SHIPPER_ORDERS/PICKUP/LOAD_SUCCESS";
export const SHIPPER_ORDERS_PICKUP_FAIL = "SHIPPER_ORDERS/PICKUP/LOAD_FAIL";
export const SHIPPER_ORDERS_PICKUP_URL = "/Shipper/Orders/Pickup";

export const SHIPPER_ORDERS_GET_ORDERS_ID_BY_QRCODE =
  "SHIPPER_ORDERS/GET_ORDERS_ID_BY_QRCODE/LOAD";
export const SHIPPER_ORDERS_GET_ORDERS_ID_BY_QRCODE_SUCCESS =
  "SHIPPER_ORDERS/GET_ORDERS_ID_BY_QRCODE/LOAD_SUCCESS";
export const SHIPPER_ORDERS_GET_ORDERS_ID_BY_QRCODE_FAIL =
  "SHIPPER_ORDERS/GET_ORDERS_ID_BY_QRCODE/LOAD_FAIL";
export const SHIPPER_ORDERS_GET_ORDERS_ID_BY_QRCODE_URL =
  "/Shipper/Orders/GetOrderIDByQRCode";
