import COLORS from "../../constans/colors";
import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");
const CARD_HEIGHT = height * 0.6;
const CARD_WIDTH = width - 60;
const SPACING_FOR_CARD_INSET = width * 0.1 - 10;

export default StyleSheet.create({
  offer: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
    textAlign: "center",
  },
  openModal: {
    backgroundColor: "#23BF08",
    padding: 10,
    borderRadius: 10,
    flex: 3,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  price: {
    position: "absolute",
    backgroundColor: COLORS.primary,
    bottom: CARD_HEIGHT + 30,
    right: 20,
    padding: 20,
    borderRadius: 10,
  },
  divider: {
    width: "100%",
    backgroundColor: COLORS.primary,
    height: 1,
    marginVertical: 10,
  },
  text_footer: {
    color: COLORS.text,
    fontWeight: "bold",
    fontSize: 14,
    marginHorizontal: 20,
    marginTop: 20,
  },
  action: {
    flexDirection: "row",
    marginTop: 10,
    borderColor: "#979797",
    padding: 13,
    borderWidth: 1,
    marginHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  action1: {
    marginTop: 10,
    padding: 15,
    backgroundColor: COLORS.primary,
    // marginHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 30,
  },

  btnGonder: {
    backgroundColor: COLORS.primary,
    marginHorizontal: 20,
    padding: 15,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 20,
    borderRadius: 10,
  },
  btnText: { color: "#ffffff", fontSize: 20, fontWeight: "bold" },

  card: {
    flexDirection: "row",
    paddingVertical: 10,
  },

  chipsScrollView: {
    position: "absolute",
    top: Platform.OS === "ios" ? 90 : 80,
    paddingHorizontal: 10,
  },
  chipsIcon: {
    marginRight: 5,
  },
  chipsItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    height: 35,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
  },
  scrollView: {
    // position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 10,
  },
  endPadding: {
    paddingRight: width - CARD_WIDTH,
  },
  card: {
    // padding: 10,
    elevation: 2,
    backgroundColor: "#FFF",
    borderRadius: 5,
    marginHorizontal: 10,
    shadowColor: "#000",
    shadowRadius: 5,
    shadowOpacity: 0.3,
    shadowOffset: { x: 2, y: -2 },
    height: CARD_HEIGHT,
    width: CARD_WIDTH,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  cardImage: {
    flex: 3,
    width: "100%",
    height: "100%",
    alignSelf: "center",
  },
  textContent: {
    flex: 2,
    padding: 10,
    marginHorizontal: 10,
  },
  baslik: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 30,
    color: COLORS.text,
  },

  cardtitle: {
    fontSize: 17,
    // marginTop: 5,
    color: COLORS.text,
  },
  cardDescription1: {
    fontSize: 20,
    textAlign: "right",
    color: COLORS.text,
    fontWeight: "bold",
  },
  markerWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 50,
    height: 50,
  },
  marker: {
    width: 30,
    height: 30,
  },
  button: {
    alignItems: "center",
    marginTop: 5,
    backgroundColor: COLORS.primary,
    borderRadius: 5,
    paddingVertical: 10,
  },
  signIn: {
    width: "100%",
    padding: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 3,
  },
  textSign: {
    fontSize: 16,
    fontWeight: "bold",
  },
  actionSearch: {
    flexDirection: "row",
    marginTop: 5,
    justifyContent: "space-around",
    borderColor: "#979797",
    padding: 13,
    borderWidth: 1,
    marginHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  container: {
    flex: 1,
  },
  view: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: Platform.OS === "ios" ? 50 : 30,
    position: "absolute",
    width: "90%",
    alignSelf: "center",
    padding: 10,
  },
  views: {
    flexDirection: "row",
    position: "absolute",
    justifyContent: "space-between",
    bottom: CARD_HEIGHT,
    right: 20,
    position: "absolute",
    width: "90%",
    alignSelf: "center",
    padding: 10,
  },
  searchBox: {
    flexDirection: "row",
    position: "absolute",
    marginTop: Platform.OS === "ios" ? 50 : 30,
    backgroundColor: COLORS.primary,
    width: "90%",
    alignSelf: "center",
    borderRadius: 5,
    padding: 10,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
  },
  chipsScrollView: {
    position: "absolute",
    top: Platform.OS === "ios" ? 90 : 80,
    paddingHorizontal: 10,
  },
  chipsIcon: {
    marginRight: 5,
  },
  chipsItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    height: 35,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
  },
  scrollView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 10,
  },
  endPadding: {
    paddingRight: width - CARD_WIDTH,
  },
  card: {
    // padding: 10,
    elevation: 2,
    backgroundColor: "#FFF",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    marginHorizontal: 10,
    shadowColor: "#000",
    shadowRadius: 5,
    shadowOpacity: 0.3,
    shadowOffset: { x: 2, y: -2 },
    height: CARD_HEIGHT,
    width: CARD_WIDTH,
    overflow: "hidden",
  },
  cardImage: {
    flex: 3,
    width: "100%",
    height: "100%",
    alignSelf: "center",
  },
  cardtitle: {
    marginTop: 20,
    fontSize: 12,
    // marginTop: 5,
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 17,
    color: COLORS.text,
  },
  cardDescription: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.text,
    textAlign: "center",
  },
  markerWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 50,
    height: 50,
  },
  marker: {
    width: 30,
    height: 30,
  },
  button: {
    alignItems: "center",
    marginTop: 5,
  },
  signIn: {
    width: "100%",
    padding: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 3,
  },
  textSign: {
    fontSize: 14,
    fontWeight: "bold",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 30,
    alignItems: "center",
  },
  mdl: {
    height: height / 2,
    borderRadius: 20,
    backgroundColor: "#ffffff",
  },
  textDesign: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
    alignItems: "center",
  },
  btnDetail: {
    backgroundColor: COLORS.primary,
    padding: 20,
    marginRight: 20,
    borderRadius: 10,
  },
});
