import COLORS from "../../constans/colors";
import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");
const ASPECT_RATIO = width / height;

export default StyleSheet.create({
  container: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginVertical: 20,
    alignItems: "center",
  },
  containerss: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginVertical: 20,
    alignItems: "center",
    justifyContent: "space-between",
  },
  txtBaslik: {
    fontWeight: "bold",
    fontSize: 20,
    color: COLORS.text,
    marginLeft: 20,
  },
  txtBasliks: {
    fontWeight: "bold",
    fontSize: 20,
    color: COLORS.text,
    marginLeft: 20,
    justifyContent: "space-between",
  },
  list: {
    width: width - 40,
    marginTop: 5,
    backgroundColor: "#fff",
    borderRadius: 10,
    alignSelf: "center",
    paddingVertical: 20,
  },
  listPrice: {
    width: width - 40,
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 10,
    alignSelf: "center",
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  baslik: {
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 8,
    color: COLORS.text,
  },
  title: {
    fontSize: 14,
    fontWeight: "500",
    marginVertical: 8,
  },
  detailPrice: {
    textAlign: "center",
    fontWeight: "bold",
    marginHorizontal: 5,
    color: COLORS.text,
    fontSize: 20,
    marginHorizontal: 20,
  },
  btnArac: {
    marginHorizontal: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F1F2F4",
    padding: 10,
    borderRadius: 5,
    flexDirection: "row",
  },
  txtYuk: {
    fontWeight: "bold",
    fontSize: 20,
    color: COLORS.text,
  },
  btnTeslim: {
    marginHorizontal: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#23BF08",
    padding: 10,
    borderRadius: 5,
    flexDirection: "row",
  },
  txtTeslim: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#fff",
  },
  chipsScrollView: {
    position: "absolute",
    top: Platform.OS === "ios" ? 90 : 80,
    paddingHorizontal: 10,
    backgroundColor: "red",
  },
  chipsIcon: {
    marginRight: 5,
  },
  chipsItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    height: 35,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 10,
  },
  scrollView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 10,
  },
  durumColor: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 10 },
  durum: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#fff",
  },
});
